name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if necessary
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change to the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the requirements file as necessary

      - name: Run tests
        run: |
          pytest  # Change this to your test command
          
      - name: Build Docker image
        run: |
          docker build -t my-image-name .  # Change to your image name

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-image-name:latest my-dockerhub-username/my-image-name:latest
          docker push my-dockerhub-username/my-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip "docker pull my-dockerhub-username/my-image-name:latest && docker run -d my-dockerhub-username/my-image-name:latest"
